In [14]:
import pandas as pd

url = 'https://en.wikipedia.org/wiki/List_of_high-speed_trains'
tables = pd.read_html(url)
table = tables[1]

In [15]:
# read the images in the 'Picture' column of table 1 usin PIL and beautiful soup
from PIL import Image
from bs4 import BeautifulSoup
import requests

# load tables from the url
url = 'https://en.wikipedia.org/wiki/List_of_high-speed_trains'
html = requests.get(url).text
soup = BeautifulSoup(html, 'html.parser')
tables_r = soup.find_all('table', class_='wikitable')
# replace each table with its table body
for i in range(len(tables_r)):
    tables_r[i] = tables_r[i].find('tbody')

# getting rows
tables_r = tables_r[0].find_all('tr')[2:]

In [16]:

# getting images from the last cell of each row
images = []
for row in tables_r:
    # print first cell of each row
    try:
        images.append(row.find_all('td')[-1].find('img')['src'])
    except:
        images.append('no image')

In [17]:
# laod each image in with PIL
from PIL import Image

for i in range(100,len(images)):
    if images[i] != 'no image':
        print(images[i])
        url = 'https:' + images[i]
        img = Image.open(requests.get(url, stream=True).raw)
        filename = table[('Name', 'Name')][i].replace('/', '-')
        img.save('images/' + filename + '.png')
    else:
        # save a placeholder image
        img = Image.open('placeholder.png')
        filename = table[('Name', 'Name')][i].replace('/', '-')
        img.save('images/' + filename + '.png')

//upload.wikimedia.org/wikipedia/commons/thumb/b/b4/JRE-TEC-E5_omiya.JPG/120px-JRE-TEC-E5_omiya.JPG
//upload.wikimedia.org/wikipedia/commons/thumb/e/e2/H5%E7%B3%BB_H1%E7%B7%A8%E6%88%90_%E4%BB%99%E5%8F%B0%E9%A7%85%E5%85%A5%E7%B7%9A.JPG/120px-H5%E7%B3%BB_H1%E7%B7%A8%E6%88%90_%E4%BB%99%E5%8F%B0%E9%A7%85%E5%85%A5%E7%B7%9A.JPG

UnidentifiedImageError: cannot identify image file <_io.BytesIO object at 0x157072270>

In [ ]:
# replace character / with - in the names of the trains
table[('Name','Name')] = table[('Name','Name')].apply(lambda x: x.replace('/', '-'))

In [ ]:
# place pictures in the table
from PIL import Image
import io
# insert images as binary data
table[('Pictures', 'Pictures')] = table.apply(lambda x: Image.open('images/' + x[('Name', 'Name')] + '.png'), axis=1)

FileNotFoundError: [Errno 2] No such file or directory: 'images/Alvia Class 120, 121 (variable gauge).png'

In [ ]:
table[('Pictures', 'Pictures')] = table.apply(lambda x: 'images/' + x[('Name', 'Name')] + '.png', axis=1)

In [ ]:
#load image from dataframe
from PIL import Image
import io
img =table[('Pictures', 'Pictures')][0]
# display image
img.show()

AttributeError: 'str' object has no attribute 'show'

In [18]:
# save to proquestql database
import psycopg2

# connect to the database
conn = psycopg2.connect(
    port=5432,
    host="localhost",
    database="postgres",
    user="postgres",
    password="2903")

# export dataframe to sql
from sqlalchemy import create_engine
engine = create_engine('postgresql://postgres:2903@localhost:5432/postgres')
table.to_sql('trains', engine, if_exists='replace')

132

In [19]:
# read from sql
import pandas as pd
from sqlalchemy import create_engine
engine = create_engine('postgresql://postgres:2903@localhost:5432/postgres')
table = pd.read_sql('trains', engine)

AttributeError: 'OptionEngine' object has no attribute 'execute'

In [20]:
table

                                      Name  \
                                      Name
0           Acela Express (1st generation)
1                                Afrosiyob
2                                  AGV 575
3                            Alfa Pendular
4    Alvia Class 120, 121 (variable gauge)
..                                     ...
127                                    X74
128                                    ER1
129                                    X80
130                         Zefiro Express
131                                  Z-TER

                                             Operators             Family  \
                                             Operators             Family
0                                               Amtrak  TGV & LRC derived
1                                  Uzbekistan Railways          Talgo 250
2                                                  NTV                AGV
3                                                   CP          Pendolino
4                                                Renfe          CAF Cepia
..                                                 ...                ...
127                                               MTRX      Stadler FLIRT
128  Mälardalstrafik  Upplands Lokaltrafik  Tågkomp...      Stadler Dosto
129                                         Västtrafik             Zefiro
130                                                 SJ             Zefiro
131                                               SNCF                NaN

                         Manufacturer  \
                         Manufacturer
0                   Alstom Bombardier
1                               Talgo
2                              Alstom
3    Fiat Ferroviaria Adtranz Siemens
4                          CAF Alstom
..                                ...
127                      Stadler Rail
128                      Stadler Rail
129                        Bombardier
130                            Alstom
131                 Alstom Bombardier

                                     Power supply Maximum speed (km/h)  \
                                     Power supply             Operated
0    25 kV 60 Hz AC 12 kV 60 Hz AC 12 kV 25 Hz AC        240 (150 mph)
1                                  25 kV 50 Hz AC                  250
2                          25 kV 50 Hz AC 3 kV DC                  300
3                                  25 kV 50 Hz AC               220[1]
4                          25 kV 50 Hz AC 3 kV DC                  250
..                                            ...                  ...
127                              15 kV 16.7 Hz AC                  200
128                                      6 000 kW                  200
129                              15 kV 16.7 Hz AC                  NaN
130                              15 kV 16.7 Hz AC                  NaN
131                      25 kV 50 Hz AC 1.5 kV DC                  200

                                  In Service Picture
          Designed         Record In Service Picture
0    266 (165 mph)  266 (165 mph)       2000     NaN
1              250            NaN       2011     NaN
2              360            NaN       2012     NaN
3              250            NaN    1999[1]     NaN
4              250            NaN       2004     NaN
..             ...            ...        ...     ...
127            200            NaN       2015     NaN
128            200            NaN       2019     NaN
129            200            NaN       2023     NaN
130            250            NaN       2026     NaN
131            200            NaN       2003     NaN

[132 rows x 10 columns]